deadzone = 0.2

#Motor IDs
LEFT_LEADER_ID = 13
LEFT_MIDDLE_ID = 1
LEFT_FOLLOWER_ID = 3
RIGHT_LEADER_ID = 14
RIGHT_MIDDLE_ID = 15
RIGHT_FOLLOWER_ID = 2
SHOOTER_ID = 7

# Climber Components
WINCH_LEFT_ID = 4
WINCH_RIGHT_ID = 5

SOLENOID_LEFT_FORWARD_ID = 0
SOLENOID_LEFT_REVERSE_ID = 1
SOLENOID_RIGHT_FORWARD_ID = 2
SOLENOID_RIGHT_REVERSE_ID = 3